"""AAF Python SDK — thin client over the AAF HTTP API.

Quick start
-----------

>>> import asyncio
>>> from aaf import AsyncAAFClient
>>>
>>> async def main():
...     async with AsyncAAFClient("http://localhost:8000") as cli:
...         await cli.login("admin@example.com", "secret")
...         resp = await cli.tasks.create(workflow="research", query="MoE survey")
...         async for event in cli.tasks.stream(resp.task_id):
...             print(event.type, event.data)
...
>>> asyncio.run(main())  # doctest: +SKIP

See ``examples/`` next to this package for runnable scripts.
"""

from __future__ import annotations

from ._version import __version__
from .auth import AsyncAuthAPI, AuthAPI
from .client import (
    DEFAULT_TIMEOUT,
    SSE_TIMEOUT,
    USER_AGENT,
    AAFClient,
    AsyncAAFClient,
    parse_sse_block,
)
from .exceptions import (
    AAFClientError,
    APIError,
    AuthenticationError,
    NotFoundError,
    PermissionDeniedError,
    ServerError,
    ValidationError,
)
from .documents import AsyncDocumentsAPI, DocumentsAPI
from .manuscripts import AsyncManuscriptsAPI, ManuscriptsAPI
from .memory import (
    AsyncHeuristicsAPI,
    AsyncKnowledgeAPI,
    AsyncMemoryAPI,
    HeuristicsAPI,
    KnowledgeAPI,
    MemoryAPI,
)
from .models import (
    AuthConfig,
    CreateTaskResponse,
    DocChunk,
    DocChunkHit,
    DocumentSourceKind,
    ExecutePlanResponse,
    Heuristic,
    HeuristicDomain,
    HeuristicVerdict,
    IngestDocumentResponse,
    IngestEvolution,
    IngestExtracted,
    IngestPaperResponse,
    KnowledgeDocument,
    LinkType,
    Manuscript,
    ManuscriptEnvelope,
    ManuscriptKind,
    ManuscriptStatus,
    ManuscriptVersion,
    MemoryStats,
    NodeKind,
    NodeOutcome,
    NodeStatus,
    OnFailure,
    PaperCard,
    PlanDAG,
    PlanNode,
    Proposal,
    ProposalAction,
    ProposalAuditEvent,
    ProposalListResponse,
    ProposalStatus,
    ProposerKind,
    PublicUser,
    Reflection,
    ReflectionType,
    RiskLevel,
    RollbackResponse,
    SkillDetail,
    SkillDryRunResponse,
    SkillForCompile,
    SkillInstallInput,
    SkillInvocation,
    SkillInvocationStatus,
    SkillReloadResponse,
    SkillScriptDescriptor,
    SkillScriptInput,
    SkillScriptSource,
    SkillsForCompileResponse,
    SkillSummary,
    SourceKind,
    StrategyBlock,
    StreamEvent,
    SynthesisNote,
    TaskEventRecord,
    TaskRecord,
    TaskStatus,
    TokenResponse,
    ToolForCompile,
    ToolInfo,
    TypedLink,
    UserRole,
    ValidatePlanResponse,
    VersionInfo,
    WorkflowInfo,
)
from .planner import AsyncPlannerAPI, PlannerAPI
from .proposals import AsyncProposalsAPI, ProposalsAPI
from .skills import AsyncSkillsAPI, SkillsAPI
from .tasks import AsyncTasksAPI, TasksAPI
from .tools import AsyncToolsAPI, ToolsAPI
from .workflows import AsyncWorkflowsAPI, WorkflowsAPI

__all__ = [
    "DEFAULT_TIMEOUT",
    "SSE_TIMEOUT",
    "USER_AGENT",
    "AAFClient",
    "AAFClientError",
    "APIError",
    "AsyncAAFClient",
    "AsyncAuthAPI",
    "AsyncDocumentsAPI",
    "AsyncHeuristicsAPI",
    "AsyncKnowledgeAPI",
    "AsyncManuscriptsAPI",
    "AsyncMemoryAPI",
    "AsyncPlannerAPI",
    "AsyncProposalsAPI",
    "AsyncSkillsAPI",
    "AsyncTasksAPI",
    "AsyncToolsAPI",
    "AsyncWorkflowsAPI",
    "AuthAPI",
    "AuthConfig",
    "AuthenticationError",
    "CreateTaskResponse",
    "DocChunk",
    "DocChunkHit",
    "DocumentSourceKind",
    "DocumentsAPI",
    "ExecutePlanResponse",
    "Heuristic",
    "HeuristicDomain",
    "HeuristicVerdict",
    "HeuristicsAPI",
    "IngestDocumentResponse",
    "IngestEvolution",
    "IngestExtracted",
    "IngestPaperResponse",
    "KnowledgeAPI",
    "KnowledgeDocument",
    "LinkType",
    "Manuscript",
    "ManuscriptEnvelope",
    "ManuscriptKind",
    "ManuscriptStatus",
    "ManuscriptVersion",
    "ManuscriptsAPI",
    "MemoryAPI",
    "MemoryStats",
    "NodeKind",
    "NodeOutcome",
    "NodeStatus",
    "NotFoundError",
    "OnFailure",
    "PaperCard",
    "PermissionDeniedError",
    "PlanDAG",
    "PlanNode",
    "PlannerAPI",
    "Proposal",
    "ProposalAction",
    "ProposalAuditEvent",
    "ProposalListResponse",
    "ProposalStatus",
    "ProposalsAPI",
    "ProposerKind",
    "PublicUser",
    "Reflection",
    "ReflectionType",
    "RiskLevel",
    "RollbackResponse",
    "ServerError",
    "SkillDetail",
    "SkillDryRunResponse",
    "SkillForCompile",
    "SkillInstallInput",
    "SkillInvocation",
    "SkillInvocationStatus",
    "SkillReloadResponse",
    "SkillScriptDescriptor",
    "SkillScriptInput",
    "SkillScriptSource",
    "SkillSummary",
    "SkillsAPI",
    "SkillsForCompileResponse",
    "SourceKind",
    "StrategyBlock",
    "StreamEvent",
    "SynthesisNote",
    "TaskEventRecord",
    "TaskRecord",
    "TaskStatus",
    "TasksAPI",
    "TokenResponse",
    "ToolForCompile",
    "ToolInfo",
    "ToolsAPI",
    "TypedLink",
    "UserRole",
    "ValidatePlanResponse",
    "ValidationError",
    "VersionInfo",
    "WorkflowInfo",
    "WorkflowsAPI",
    "__version__",
    "parse_sse_block",
]
